# Generated by Django 4.0.2 on 2022-02-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_ref', models.CharField(max_length=35, unique=True, verbose_name='Transaction Reference')),
                ('account', models.CharField(max_length=25, verbose_name='Account Number')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'b_Transaction',
                'verbose_name_plural': 'Bank Transactions',
            },
        ),
        migrations.CreateModel(
            name='FileUploaded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='parterns transactions', max_length=20, verbose_name='Partners File')),
                ('file', models.FileField(upload_to='static/files')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Partner File',
                'verbose_name_plural': 'Partners Files',
            },
        ),
        migrations.CreateModel(
            name='PartnersTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_ref', models.CharField(max_length=35, verbose_name='Transaction Reference')),
                ('account', models.CharField(max_length=25, verbose_name='Account Number')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('institution', models.CharField(max_length=20, verbose_name='Partner')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'partners_transaction',
                'verbose_name_plural': 'partners transactions',
            },
        ),
    ]
